// Code generated by goctl. DO NOT EDIT.
package types

type JizhangAddReq struct {
	Name      string `form:"name,optional"`
	Num       string `form:"num,optional"`
	Time      int64  `form:"time,optional"`
	Status    int    `form:"status,optional"`
	Leixing   string `form:"leixing,optional"`
	Leixingid string `form:"leixingid,optional"`
	Puber     string `form:"puber,optional"`
	Ty        string `form:"ty,optional"`
	Tip       string `form:"tip,optional"`
}

type JizhangSearchReq struct {
	Puber string `form:"puber,optional"`
}

type JizhangUpdateReq struct {
	Id        int    `form:"id,optional"`
	Name      string `form:"name,optional"`
	Num       string `form:"num,optional"`
	Time      int64  `form:"time,optional"`
	Status    int    `form:"status,optional"`
	Leixing   string `form:"leixing,optional"`
	Leixingid string `form:"leixingid,optional"`
	Puber     string `form:"puber,optional"`
	Ty        string `form:"ty,optional"`
	Tip       string `form:"tip,optional"`
}

type JizhangLeixingAddReq struct {
	Name  string `form:"name"`
	Puber string `form:"puber,optional"`
}

type JizhangLeixingSearchReq struct {
	Puber string `form:"puber,optional"`
}

type JizhangLeixingUpdateReq struct {
	Id     int    `form:"id,optional"`
	Name   string `form:"name,optional"`
	Status int    `form:"status,optional"`
}

type Resp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
