// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/superyyk/mayi_rpc/app/workers/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/worker/add",
				Handler: AddworkerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/update",
				Handler: UpdateworkerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/search",
				Handler: SearchworkerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/ty/add",
				Handler: AddWorkertyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/ty/search",
				Handler: SearchWorkertyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/ty/del",
				Handler: DelWorkertyHandler(serverCtx),
			},
		},
	)
}
