// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mayi/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/get_user_info",
				Handler: getUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/change_pass",
				Handler: getChangePassHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: getLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/loginsms",
				Handler: getLoginSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/regist",
				Handler: getRegistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sms",
				Handler: getSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/onekey",
				Handler: getOneKeyHandler(serverCtx),
			},
		},
	)
}
