Name: products
Host: 0.0.0.0
Port: 10020

Redis:
  Host: 127.0.0.1:6379
  Type: node
  Pass: ""
DB:
  DataSource: root:yyk*2012@tcp(127.0.0.1:3306)/yunboss?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
Cache:
  - Host: 127.0.0.1:6379
    Pass: ""