// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mayi/app/liucheng/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/step/add",
				Handler: stepAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/step/search",
				Handler: stepSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/step/update",
				Handler: stepUpdateHandler(serverCtx),
			},
		},
	)
}
