// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mayi/app/kehu/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/kehu/add",
				Handler: AddKehuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kehu/update",
				Handler: UpdateKehuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kehu/search",
				Handler: SearchKehuHandler(serverCtx),
			},
		},
	)
}
