// Code generated by goctl. DO NOT EDIT.
package types

type SetReq struct {
	Num    int    `form:"num"`
	Userid string `form:"userid"`
}

type GetReq struct {
	Userid string `form:"userid"`
}

type PubReq struct {
	Topic string `form:"topic"`
	Uid   string `form:"uid"`
}

type ConsumerReq struct {
	Topic string `form:"topic"`
}

type Resp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
