// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mayi/app/jizhang/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/add",
				Handler: jizhangAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/search",
				Handler: jizhangSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/update",
				Handler: jizhangUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/leixing/add",
				Handler: jizhangLeixingAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/leixing/search",
				Handler: jizhangLeixingSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jizhang/leixing/update",
				Handler: jizhangLeixingUpdateHandler(serverCtx),
			},
		},
	)
}
