// Code generated by goctl. DO NOT EDIT.
// Source: skill.proto

package server

import (
	"context"

	"mayi/app/skill/rpc/internal/logic"
	"mayi/app/skill/rpc/internal/svc"
	"mayi/app/skill/rpc/types/skill"
)

type SkillServer struct {
	svcCtx *svc.ServiceContext
	skill.UnimplementedSkillServer
}

func NewSkillServer(svcCtx *svc.ServiceContext) *SkillServer {
	return &SkillServer{
		svcCtx: svcCtx,
	}
}

func (s *SkillServer) GetSkill(ctx context.Context, in *skill.SkillRequest) (*skill.Rsp, error) {
	l := logic.NewGetSkillLogic(ctx, s.svcCtx)
	return l.GetSkill(in)
}

func (s *SkillServer) SetSkill(ctx context.Context, in *skill.SetReq) (*skill.SetRsp, error) {
	l := logic.NewSetSkillLogic(ctx, s.svcCtx)
	return l.SetSkill(in)
}
