// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package smscode

import (
	"context"

	"github.com/superyyk/mayi_rpc/sms/rpc/types/sms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetCodeRequest = sms.GetCodeRequest
	GetResponse    = sms.GetResponse

	SmsCode interface {
		GetCode(ctx context.Context, in *GetCodeRequest, opts ...grpc.CallOption) (*GetResponse, error)
	}

	defaultSmsCode struct {
		cli zrpc.Client
	}
)

func NewSmsCode(cli zrpc.Client) SmsCode {
	return &defaultSmsCode{
		cli: cli,
	}
}

func (m *defaultSmsCode) GetCode(ctx context.Context, in *GetCodeRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	client := sms.NewSmsCodeClient(m.cli.Conn())
	return client.GetCode(ctx, in, opts...)
}
