// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Tel  string `form:"tel"`
	Pass string `form:"pass"`
}

type LoginResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type LoginSmsReq struct {
	Tel  string `form:"tel"`
	Code string `form:"code"`
	Uid  string `form:"uid"`
}

type LoginSmsResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type RegistReq struct {
	Tel  string `form:"tel"`
	Code string `form:"code"`
	Pass string `form:"pass"`
}

type RegistResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type SmsReq struct {
	Tel string `form:"tel"`
}

type SmsResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type OneKeyReq struct {
	Tel    string `form:"tel"`
	Token  string `form:"token"`
	Openid string `form:"openid"`
}

type OneKeyResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type ChangePassReq struct {
	Tel  string `form:"tel"`
	Code string `form:"code"`
	Uid  string `form:"uid"`
	Pass string `form:"pass"`
}

type ChangePassResp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type Resp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type LoadUserReq struct {
	UserUid string `form:"uid,optional"`
}
