// Code generated by goctl. DO NOT EDIT.
package types

type UpReq struct {
	UserUid string `form:"user_uuid"`
	File    string `form:"file,optional"`
}

type Resp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
