// Code generated by goctl. DO NOT EDIT.
package types

type AddTyReq struct {
	Uid  string `form:"uid,optional"`
	Name string `form:"name,optional"`
}

type SearchTyReq struct {
	Uid string `form:"uid,optional"`
}

type DelTyReq struct {
	Uid string `form:"uid,optional"`
}

type AddReq struct {
	Id         int    `form:"id,optional"`
	Name       string `form:"name"`
	Age        int    `form:"age,optional"`
	Uid        string `form:"uid,optional"`
	Status     int    `form:"status,optional,default=0"`
	Tel        string `form:"tel,optional"`
	Ty         string `form:"ty,optional"`
	Salary     string `form:"salary,optional"`
	Time       string `form:"time,optional"`
	Puber      string `form:"puber,optional"`
	Tip        string `form:"tip,optional"`
	Workertyid string `form:"workerty_id,optional"`
	Workerty   string `form:"workerty,optional"`
}

type Resp struct {
	Res  string      `json:"res"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UpdateReq struct {
	Id         int    `form:"id,optional"`
	Name       string `form:"name,optional"`
	Age        int    `form:"age,optional"`
	Uid        string `form:"uid,optional"`
	Status     int    `form:"status,optional,default=0"`
	Tel        string `form:"tel,optional"`
	Ty         string `form:"ty,optional"`
	Salary     string `form:"salary,optional"`
	Time       string `form:"time,optional"`
	Puber      string `form:"puber,optional"`
	Tip        string `form:"tip,optional"`
	Workertyid string `form:"workerty_id,optional"`
	Workerty   string `form:"workerty,optional"`
}

type SearchReq struct {
	Uid string `form:"uid"`
}
